[package]
name = "sres_emulator"
version = "0.1.0"
authors = ["Dennis Kempin <dennis.kempin@gmail.com>"]
edition = "2021"
rust-version = "1.65"

[lib]
bench = false

[features]
debug_log = []

[dependencies]
anyhow = "1.0"
intbits = "0.2"
itertools = "0.10"
lazy_static = "1"
packed_struct = "0.10"
thiserror = "1.0"
snafu = "*"
num-traits = "*"

[dev-dependencies]
tempfile = "*"
pretty_assertions = "*"
criterion = "*"


[[bench]]
name = "cpu_benches"
harness = false

