# Use Docker image used in devcontainer
image:
  file: .devcontainer/Dockerfile

# Run tests as the default task, since there is no program yet.
tasks:
  - name: "Run tests"
    init: git lfs pull && cargo test --no-run
    command: cargo watch -x "nextest run"
