//! High level testing focused on the CPU.
//!
//! Most tests will execute a test rom and compare cycle for cycle against a tracelog generated by BSNES.
use std::fs::File;
use std::io;
use std::io::BufRead;
use std::path::Path;
use std::path::PathBuf;

use anyhow::Result;
use pretty_assertions::assert_eq;
use sres_emulator::common::bus::Bus;
use sres_emulator::common::logging;
use sres_emulator::common::util::format_memory;
use sres_emulator::components::cartridge::Cartridge;
use sres_emulator::components::cpu::CpuState;
use sres_emulator::components::spc700::Spc700State;
use sres_emulator::debugger::EventFilter;
use sres_emulator::CpuT;
use sres_emulator::SyncSystem;
use sres_emulator::System;

#[test]
pub fn test_krom_adc() {
    run_rom_test("krom_adc");
}

#[test]
pub fn test_krom_and() {
    run_rom_test("krom_and");
}

#[test]
pub fn test_krom_asl() {
    run_rom_test("krom_asl");
}

#[test]
pub fn test_krom_bit() {
    run_rom_test("krom_bit");
}

#[test]
pub fn test_krom_bra() {
    run_rom_test("krom_bra");
}

#[test]
pub fn test_krom_cmp() {
    run_rom_test("krom_cmp");
}

#[test]
pub fn test_krom_dec() {
    run_rom_test("krom_dec");
}

#[test]
pub fn test_krom_eor() {
    run_rom_test("krom_eor");
}

#[test]
pub fn test_krom_inc() {
    run_rom_test("krom_inc");
}

#[test]
pub fn test_krom_jmp() {
    run_rom_test("krom_jmp");
}

#[test]
pub fn test_krom_ldr() {
    run_rom_test("krom_ldr");
}

#[test]
pub fn test_krom_lsr() {
    run_rom_test("krom_lsr");
}

#[test]
pub fn test_krom_mov() {
    run_rom_test("krom_mov");
}

#[test]
#[ignore = "Instructions not implemented yet"]
pub fn test_krom_msc() {
    run_rom_test("krom_msc");
}

#[test]
pub fn test_krom_ora() {
    run_rom_test("krom_ora");
}

#[test]
pub fn test_krom_phl() {
    run_rom_test("krom_phl");
}

#[test]
pub fn test_krom_psr() {
    run_rom_test("krom_psr");
}

#[test]
pub fn test_krom_ret() {
    run_rom_test("krom_ret");
}

#[test]
pub fn test_krom_rol() {
    run_rom_test("krom_rol");
}

#[test]
pub fn test_krom_ror() {
    run_rom_test("krom_ror");
}

#[test]
pub fn test_krom_sbc() {
    run_rom_test("krom_sbc");
}

#[test]
pub fn test_krom_str() {
    run_rom_test("krom_str");
}

#[test]
pub fn test_krom_trn() {
    run_rom_test("krom_trn");
}

#[test]
pub fn test_ppu_timing() {
    run_rom_test("ppu_timing");
}

#[test]
#[ignore = "WIP"]
pub fn test_play_noise() {
    run_rom_test_with_spc700_trace("play_noise");
}

fn run_rom_test(test_name: &str) {
    logging::test_init(false);

    let root_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let trace_path = root_dir.join(format!("tests/rom_tests/{test_name}-trace.log.xz"));
    let rom_path = root_dir.join(format!("tests/rom_tests/{test_name}.sfc"));

    let mut system = SyncSystem::with_cartridge(&Cartridge::with_sfc_file(&rom_path).unwrap());
    // CPUMSC reads 0x93 from $000000 at the first instruction. I cannot figure out why, it
    // should be mapped to RAM.
    system.cpu.bus.cycle_write_u8(0x000000.into(), 0x93);
    system.cpu.reset();

    system.debugger().enable();
    system.debugger().add_log_point(EventFilter::CpuStep);

    for (line_num, expected_line) in trace_log_from_xz_file(&trace_path).unwrap().enumerate() {
        system.execute_one_instruction();
        let actual_line = system
            .debugger()
            .drain_cpu_steps()
            .into_iter()
            .next()
            .unwrap();
        let expected_line = expected_line.unwrap();
        assert_cpu_trace_eq(line_num, expected_line, actual_line);
    }
}

fn run_rom_test_with_spc700_trace(test_name: &str) {
    logging::test_init(true);

    let root_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let trace_path = root_dir.join(format!("tests/rom_tests/{test_name}-trace.log.xz"));
    let rom_path = root_dir.join(format!("tests/rom_tests/{test_name}.sfc"));

    let mut system = SyncSystem::with_cartridge(&Cartridge::with_sfc_file(&rom_path).unwrap());

    // CPUMSC reads 0x93 from $000000 at the first instruction. I cannot figure out why, it
    // should be mapped to RAM.
    system.cpu.bus.bus_write(0x000000.into(), 0x93);

    system.debugger().enable();
    system.debugger().add_log_point(EventFilter::Spc700Step);
    system.debugger().add_log_point(EventFilter::CpuStep);

    let mut expected_spc_pending = Vec::new();
    let mut actual_spc_pending = Vec::new();
    let mut cpu_line_num = 0usize;

    for expected_line in mixed_trace_log_from_xz_file(&trace_path).unwrap() {
        match expected_line.unwrap() {
            MixedTrace::Spc700(expected_spc) => expected_spc_pending.push(expected_spc),
            MixedTrace::Cpu(expected_cpu) => {
                system.execute_one_instruction();
                actual_spc_pending.extend(system.debugger().drain_spc700_steps());
                let actual_cpu = system
                    .debugger()
                    .drain_cpu_steps()
                    .into_iter()
                    .next()
                    .unwrap();

                assert_cpu_trace_eq(cpu_line_num, expected_cpu, actual_cpu.clone());
                if is_cpu_apuio_access(&actual_cpu) {
                    assert_spc_pending_eq(cpu_line_num, &expected_spc_pending, &actual_spc_pending);
                    expected_spc_pending.clear();
                    actual_spc_pending.clear();
                }
                cpu_line_num += 1;
            }
        }
    }

    assert_spc_pending_eq(cpu_line_num, &expected_spc_pending, &actual_spc_pending);
}

fn assert_cpu_trace_eq(_i: usize, mut expected: CpuState, mut actual: CpuState) {
    // TODO: This emulator does not implement open bus reads, which means that memory values shown
    // in the trace on write-only MMIO registers will not be correct.
    actual.instruction.effective_addr = None;
    expected.instruction.effective_addr = None;

    assert_eq!(actual.to_string(), expected.to_string());
}

fn assert_spc_trace_eq(_i: usize, mut expected: Spc700State, mut actual: Spc700State) {
    actual.instruction.operand_str = None;
    expected.instruction.operand_str = None;
    assert_eq!(actual.to_string(), expected.to_string());
}

fn is_cpu_apuio_access(cpu: &CpuState) -> bool {
    cpu.instruction
        .effective_addr
        .map(|addr| (0x2140..=0x217F).contains(&addr.offset))
        .unwrap_or(false)
}

fn assert_spc_pending_eq(cpu_line_num: usize, expected: &[Spc700State], actual: &[Spc700State]) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "SPC checkpoint mismatch at CPU line {cpu_line_num}: actual {} steps, expected {} steps",
        actual.len(),
        expected.len()
    );

    for (spc_idx, (expected_spc, actual_spc)) in expected.iter().zip(actual.iter()).enumerate() {
        assert_spc_trace_eq(
            cpu_line_num * 100_000 + spc_idx,
            expected_spc.clone(),
            actual_spc.clone(),
        );
    }
}

#[test]
pub fn test_dma_vram() {
    // This rom will generate a test sequence 0x00..0xFF in WRAM at 0x0000, then copies it into VRAM via
    // a DMA transfer and copies it back into WRAM at 0x0100.
    let cpu = run_test_rom("dma_vram");
    let expected: Vec<u8> = (0x00..=0xFF).collect();

    // Validate the test sequence at 0x0000
    assert_eq!(
        format_memory(&cpu.bus.peek_range(0x0000..=0x00FF)),
        format_memory(&expected),
    );

    // Validate the test sequence after it's copied back into WRAM at 0x0100
    assert_eq!(
        format_memory(&cpu.bus.peek_range(0x0100..=0x01FF)),
        format_memory(&expected),
    );
}

#[test]
pub fn test_dma_cgram() {
    // This rom will generate a test sequence 0x00..0xFF in WRAM at 0x0000, then copies it into CGRAM via
    // a DMA transfer and copies it back into WRAM at 0x0100.
    let cpu = run_test_rom("dma_cgram");
    let expected: Vec<u8> = (0x00..=0xFF).collect();

    // Validate the test sequence at 0x0000
    assert_eq!(
        format_memory(&cpu.bus.peek_range(0x0000..=0x00FF)),
        format_memory(&expected),
    );

    // Validate the test sequence after it's copied back into WRAM at 0x0100
    assert_eq!(
        format_memory(&cpu.bus.peek_range(0x0100..=0x01FF)),
        format_memory(&expected),
    );
}

#[test]
pub fn test_dma_oam() {
    // This rom will generate a test sequence 0x00..0xFF in WRAM at 0x0000, then copies it into OAM via
    // a DMA transfer and copies it back into WRAM at 0x0100.
    let cpu = run_test_rom("dma_oam");
    let expected: Vec<u8> = (0x00..=0xFF).collect();

    // Validate the test sequence at 0x0000
    assert_eq!(
        format_memory(&cpu.bus.peek_range(0x0000..=0x00FF)),
        format_memory(&expected),
    );

    // Validate the test sequence after it's copied back into WRAM at 0x0100
    assert_eq!(
        format_memory(&cpu.bus.peek_range(0x0100..=0x01FF)),
        format_memory(&expected),
    );
}

fn run_test_rom(test_name: &str) -> CpuT {
    logging::test_init(false);

    let root_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let rom_path = root_dir.join(format!("tests/rom_tests/{test_name}.sfc"));

    let mut system = System::with_cartridge(&Cartridge::with_sfc_file(&rom_path).unwrap());
    system.cpu.reset();

    while !system.cpu.halted() {
        system.cpu.step();
    }
    system.cpu
}

pub fn trace_log_from_xz_file(path: &Path) -> Result<impl Iterator<Item = Result<CpuState>>> {
    use xz2::read::XzDecoder;
    let file = File::open(path)?;
    let decoder = XzDecoder::new(file);
    let trace_reader = io::BufReader::new(decoder);
    Ok(trace_reader
        .lines()
        .map(|l| CpuState::parse_mesen_trace(&l?)))
}

#[derive(Debug, PartialEq)]
enum MixedTrace {
    Cpu(CpuState),
    Spc700(Spc700State),
}

impl std::fmt::Display for MixedTrace {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            MixedTrace::Cpu(state) => write!(f, "{}", state),
            MixedTrace::Spc700(state) => write!(f, "{}", state),
        }
    }
}

fn mixed_trace_log_from_xz_file(path: &Path) -> Result<impl Iterator<Item = Result<MixedTrace>>> {
    use xz2::read::XzDecoder;
    let file = File::open(path)?;
    let decoder = XzDecoder::new(file);
    let trace_reader = io::BufReader::new(decoder);
    Ok(trace_reader.lines().map(|l| {
        let l = l?;
        Ok(if l.len() < 100 {
            MixedTrace::Spc700(Spc700State::parse_mesen_trace(&l)?)
        } else {
            MixedTrace::Cpu(CpuState::parse_mesen_trace(&l)?)
        })
    }))
}
